version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - db
    links:
      - db


  db:
    image: opavlova/db-mysql:5.7-test
    ports:
      - "13306:3306"

